deployment = "deployment.toml"

[[contracts]]
name = "anyone-can-spend"
template_type = "Rust"

[[contracts]]
name = "deposit-lock"
template_type = "Rust"

[[contracts]]
name = "parent-bridge"
template_type = "Rust"

[[contracts]]
name = "audit-delay"
template_type = "Rust"



