[[cells]]
name = "parent-bridge"
enable_type_id = false
location = { file = "build/release/parent-bridge" }

[[cells]]
name = "deposit-lock"
enable_type_id = false
location = { file = "build/release/deposit-lock" }

[[cells]]
name = "anyone-can-spend"
enable_type_id = false
location = { file = "build/release/anyone-can-spend" }

[[cells]]
name = "audit-delay"
enable_type_id = false
location = { file = "build/release/audit-delay" }
#
# # reference to on-chain cells
# [[cells]]
# name = "genesis_cell"
# enable_type_id = false
# location = { tx_hash = "0x92b197aa1fba0f63633922c61c92375c9c074a93e85963554f5499fe1450d0e5", index = 0 }
 

# # Dep group cells
# [[dep_groups]]
# name = "my_dep_group"
# cells = [
#   "my_cell",
#   "genesis_cell"
# ]

# # Replace with your own lock if you want to unlock deployed cells.
# # For example the secp256k1 lock
[lock]
code_hash = "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8"
args = "0x0000000000000000000000000000000000000000"
hash_type = "type"

