[package]
name = "parent-bridge"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
blake2b-rs = "0.1.5"

[dependencies]
ckb-std = "0.6.0"
k256 = { version="0.5.10", default-features = false, features = ["ecdsa", "keccak256"] }
sha3 = { version="0.9", default-features = false }
hex = { version = "0.4", default-features = false }
ecdsa = {version= "0.8.5", default-features = false }
elliptic-curve = { version = "0.6.6", default-features = false }

[profile.release]
overflow-checks = true
opt-level = 's'
lto = true
codegen-units = 1
panic = 'abort'
